---
- name: Zabbix MSSQL check
  hosts: windows
  tasks:
    - name: Create scripts dir
      win_file:
        path: 'C:\Zabbix\scripts'
        state: directory

    - name: Transfer scripts
      win_copy:
        src: '{{ playbook_dir }}/../files/win-zabbix-mssql/scripts/'
        dest: C:\Zabbix\scripts\

    - name: Transfer config
      win_copy:
        src: '{{ playbook_dir }}/../files/win-zabbix-mssql/userparameter_mssql.conf'
        dest: C:\Zabbix\conf\conf.d\userparameter_mssql.conf

    - name: Restart zabbix agent
      win_service:
        name: 'Zabbix Agent'
        state: restarted
